help: error
fetch: error
backup: error
update_config: error
all: error
build: error
install: error
deinstall: error
uninstall: error
clean: error
distclean: error
diffs: error
sorry: error
package: error
list_files: error
print_all: error
error:
	@echo "ISDN4BSD does no longer support versions of FreeBSD prior to v8."

#--HPS
