# $FreeBSD: src/sys/modules/ulpt/Makefile,v 1.14 2005/06/04 10:58:38 schweikh Exp $

.PATH: ${.CURDIR}/../../dev/usb2

KMOD=	ulpt
SRCS=	bus_if.h device_if.h opt_usb.h _ulpt.c usbdevs.h

.include <bsd.kmod.mk>
