# $FreeBSD: src/sys/modules/uhid/Makefile,v 1.14 2005/06/04 10:58:38 schweikh Exp $

.PATH: ${.CURDIR}/../../dev/usb2

KMOD=	uhid
SRCS=	bus_if.h device_if.h opt_usb.h _uhid.c usbdevs.h

.include <bsd.kmod.mk>
