
SUBDIR =
SUBDIR += bluetooth
SUBDIR += controller
SUBDIR += core
SUBDIR += ethernet
SUBDIR += image
SUBDIR += input
SUBDIR += misc
SUBDIR += ndis
SUBDIR += quirk
SUBDIR += serial
SUBDIR += sound
SUBDIR += storage
SUBDIR += template
SUBDIR += wlan

.include <bsd.subdir.mk>
