.\"
.\" Copyright (c) 2005-2006 Hans Petter Selasky. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: $
.\"
.Dd March 26, 2006
.Dt ISDNCONFIG 8
.Os
.Sh NAME
.Nm isdnconfig
.Nd configure ISDN4BSD
.Sh SYNOPSIS
.Nm
.Op Fl u Ar unit
.Op Fl i Ar value
.Op Fl p Ar protocol
.Op Fl r
.Op Fl n
.Op Fl t
.Op Fl a
.Op Fl D
.Op Fl E Ar enum
.Op Fl h
.Op Fl m Ar unit
.Op parameters
.Sh DESCRIPTION
.Bd -filled
The
.Nm
utility is a part of the ISDN4BSD package. This utility can be used to
configure an ISDN device by unit number. Note that
.Xr isdnd 8
can override the configuration set by this utility, and the other way
around.
.Bl -tag -width Ds
.It Fl u
Set unit number. Default is zero.
.It Fl i
Set D-channel serial number. The serial number should be a uniqe
16-bit number on a per S0-bus basis, greater than 0x7F. If not
specified, the software will select some value.
.It Fl m
Set PCM cable unit number. Default is zero.
.It Fl p
Set D-channel protocol. Default is DRVR_D_CHANNEL.
.It Fl E
Display information about enum.
.It Fl r
Reset controller.
.It Fl h
Display supported options and protocols.
.It nt_mode or Fl n 
Set layer 1 to NT- or network-mode.
.It te_mode or Fl t
Set layer 1 to TE- or terminal-mode. (default)
.It hi_pri
Set D-channel to high priority. (default)
.It lo_pri
Set D-channel to low priority.
.It up or Fl a
Manually activate Layer 1.
.It down or Fl D
Manually deactivate Layer 1.
.It pwr_save
Enable power saving. (default)
.It pwr_on
Disable power saving.
.It poll_mode
Set polled interrupt mode.
.It intr_mode
Set standard interrupt mode. (default)
.It pcm_32
Select 32-slot PCM mode.
.It pcm_64
Select 64-slot PCM mode.
.It pcm_128
Select 128-slot PCM mode.
.It pcm_master
Select PCM master mode. In this mode the ISDN device 
generates its own clock.
.It pcm_slave
Select PCM slave mode. In this mode the ISDN device 
gets its clock from another ISDN device, through a 
direct cable connection.
.It pcm_map
Set PCM cable mapping.
.It t1_mode
Select T1 cable mode, if supported by hardware.
.It e1_mode
Select E1 cable mode, if supported by hardware (default).
.El
.Ed
.Sh EXAMPLES
The command:
.Bd -literal -offset indent
isdnconfig -u 0 -p DRVR_DSS1_NT
.Ed
.Pp
selects NT mode and the DSS1 multipoint to point driver, for passive
ISDN controller 0. The command:
.
.Bd -literal -offset indent
isdnconfig -u 0 -p DRVR_DSS1_NT pwr_on -u 1 -p DRVR_DSS1_NT pwr_on
.Ed
.Pp
selects NT mode and the DSS1 multipoint to point driver, for passive
ISDN controller 0 and 1, and disables power saving. The command:
.
.Bd -literal -offset indent
isdnconfig -m 0 pcm_32 \\
           -m 1 pcm_64 \\
           -u 0 pcm_map 0 -1 1 end pcm_slave
.Ed
.Pp
sets PCM cable 0 to a size of 32 PCM slots, 
sets PCM cable 1 to a size of 64 PCM slots,
sets PCM map to use PCM cable 0 for the first bi-directional pin,
sets PCM map to use no PCM cable for the second bi-directional pin,
sets PCM map to use PCM cable 1 for the third bi-directional pin and
selects PCM slave mode for controller 0. The command:
.
.Bd -literal -offset indent
isdnconfig -m 0 pcm_64 \\
           -m 1 pcm_64 \\
           -u 8 pcm_64 pcm_map 0 1 end pcm_master te_mode \\
           -u 9 pcm_64 pcm_map 0 1 end pcm_master nt_mode \\
                power_on -p DRVR_DSS1_NT
.Ed
.Pp
.
sets PCM cable 0 to a size of 64 PCM slots, sets PCM cable 1 to a size
of 64 PCM slots, sets PCM speed for controller 8 and 9 to 64 PCM
slots, sets PCM first and second bi-directional pin to be used, sets
TE-mode for controller 8 and sets NT-mode for contoller 9. This
command was used to initialize the first two ports of a HFC-4S.
.
.Sh AUTHORS
The
.Nm
utility and this manpage were written by
.An Hans Petter Selasky Aq hselasky@c2i.net .
