.\"
.\" Copyright (c) 2005 Hans Petter Selasky. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: $
.\"
.Dd October 16, 2005
.Dt ISDNCONFIG 8
.Os
.Sh NAME
.Nm isdnconfig
.Nd configure ISDN4BSD
.Sh SYNOPSIS
.Nm
.Op Fl u Ar unit
.Op Fl i Ar value
.Op Fl p Ar protocol
.Op Fl E Ar enum
.Op Fl h
.Sh DESCRIPTION
.Bd -filled
The
.Nm
utility is a part of the ISDN4BSD package. This utility can be used to
configure an ISDN device by unit number. Note that
.Xr isdnd 8
can override the configuration set by this utility, and the other way
around.
.Bl -tag -width Ds
.It Fl u
Set unit number. Default is zero.
.It Fl i
Set D-channel serial number. The serial number should be a uniqe
16-bit number on a per S0-bus basis, greater than 0x7F. If not
specified, the software will select some value.
.It Fl p
Set D-channel protocol. Default is DRVR_D_CHANNEL.
.It Fl E
Get value of enum.
.It Fl h
Display supported options and protocols.
.El
.Ed
.Sh EXAMPLES
The command:
.Bd -literal -offset indent
isdnconfig -u 0 -p DRVR_DSS1_NT
.Ed
.Pp
selects NT mode and the DSS1 multipoint to point driver, for passive
ISDN controller 0.
.Sh AUTHORS
The
.Nm
utility and this manpage were written by
.An Hans Petter Selasky Aq hselasky@c2i.net .
