# $FreeBSD: src/sys/modules/ums/Makefile,v 1.14 2005/06/04 10:58:39 schweikh Exp $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ums
SRCS=	bus_if.h device_if.h opt_usb.h ums.c usbdevs.h vnode_if.h

.include <bsd.kmod.mk>
