.\"
.\" Copyright (c) 2014 Hans Petter Selasky. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.\"
.Dd August 6, 2014
.Dt CAPISERVER 8
.Os
.Sh NAME
.Nm capiserver
.Nd CAPI server daemon
.Sh SYNOPSIS
.Nm
.Op Fl B
.Op Fl b Ar address
.Op Fl p Ar port
.Op Fl h
.Sh DESCRIPTION
The
.Nm
utility is part of the ISDN4BSD package and may be used to share the
kernel CAPI device through an IP network using TCP.
Systems sharing a CAPI connection must be matched with request to CPU
register width, 32- or 64- bit and CPU endianness, bit- or little- endian.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl B
Run server in background.
.It Fl b
Bind to this address.
.It Fl p
Bind to this port.
.It Fl h
Show usage.
.El
.Sh FILES
.Bl -tag -width indent
.It Pa /dev/capi20
.El
.Sh AUTHORS
This utility was written by
.An Hans Petter Selasky Aq hps@selasky.org .
