
.include "../Makefile.sub"

SUBDIR= \
    ${HAVE_CAPITEST} \
    ${HAVE_DTMFDECODE} \
    ${HAVE_G711CONV} \
    ${HAVE_ISDNCONFIG} \
    ${HAVE_ISDNDEBUG} \
    ${HAVE_ISDNDECODE} \
    ${HAVE_ISDND} \
    ${HAVE_ISDNMONITOR} \
    ${HAVE_ISDNTELCTL} \
    ${HAVE_ISDNTEL} \
    ${HAVE_ISDNTEST} \
    ${HAVE_ISDNTRACE} \
    ${HAVE_MAN}

.include <bsd.subdir.mk>
