# $FreeBSD: src/usr.sbin/i4b/Makefile,v 1.8 2001/12/31 09:31:51 joerg Exp $

SUBDIR=	capitest dtmfdecode g711conv isdndebug \
	isdntest isdntrace man

# isdntel
# isdntelctl
# isdnd
# isdnmonitor
# isdnphone 
# isdndecode

.include <bsd.subdir.mk>

